name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    env:
     AWS_ACCESS_KEY_ID: ${{secrets.AWS_DEVOPS_ACCESS_KEY_ID}}
     AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_DEVOPS_SECRET_ACCESS_KEY}}
    runs-on: ubuntu-latest
    environment: production

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Initialicreating initial filese, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    - name: Terraform plan
      run: terraform plan

    - name: Terraform apply
      uses: hashicorp/terraform-github-action@master
       
      with: 
        args:
          apply-auto-approve
      